# divvy · config de helix (se carga con: hx --config este-archivo)
theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true          # fuerza colores 24-bit (mejor en terminal con true color)
bufferline = "multiple"
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]

[editor.lsp]
display-messages = true
